name: cool-workflow
on: [push, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
      - name: Install apt dependencies
        # nasm - ffmpeg build
        run: sudo apt-get install nasm
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install Python dependencies
        # ninja - our build system
        run: pip install ninja
        if: startsWith(matrix.os, 'ubuntu')

      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.os, 'windows')

      - uses: lukka/get-cmake@v3.28.3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure project (Linux)
        run: cmake --preset linux-vcpkg-gcc -B ./build
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build (Debug, Linux)
        run: cmake --build build --config=Debug
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build (Release, Linux)
        run: cmake --build build --config=Release
        if: startsWith(matrix.os, 'ubuntu')

      # TODO: add ASAN ("/fsanitize=address").
      - name: Configure project (Debug, Windows)
        run: cmake --preset x64-debug-vcpkg -B ./build
        if: startsWith(matrix.os, 'windows')

      - name: Build (Windows)
        run: cmake --build build
        if: startsWith(matrix.os, 'windows')

      - name: Run tests
        run: ctest --test-dir build

        # TODO: archive and send to GitHub.
