name: cool-workflow
on: [push, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "Ubuntu (Debug)"
            os: ubuntu-22.04
            preset: linux-vcpkg-gcc
            build-args: "--config Debug"
          - name: "Ubuntu (Release)"
            os: ubuntu-22.04
            preset: linux-vcpkg-gcc
            build-args: "--config Release"
          - name: "Windows (Debug)"
            os: windows-2022
            preset: x64-debug-vcpkg
            build-args: ""
          - name: "Windows (Release)"
            os: windows-2022
            preset: x64-release-vcpkg
            build-args: ""

    steps:
      - name: Install apt dependencies
        # nasm - ffmpeg build
        run: sudo apt-get install nasm
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install Python dependencies
        # ninja - our build system
        run: pip install ninja
        if: startsWith(matrix.os, 'ubuntu')

      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.os, 'windows')

      - uses: lukka/get-cmake@v3.28.3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -B ./build

      - name: Build
        run: cmake --build build ${{ matrix.build-args }}

      - name: Run tests
        run: ctest --test-dir build

        # TODO: archive and send to GitHub.
